site_name: Documentaci√≥n
site_url: https://gabriel221011.github.io/Documentacion/
docs_dir: docs
site_dir: /docs

nav:
  - Home: index.md
  - VariasCosas:
      - varios.md
  - Otros:
      - otros.md
theme: readthedocs
