site_name: Documentaci√≥n
site_url: https://gabriel221011.github.io/Documentacion/
docs_dir: docs
site_dir: /docs

nav:
  - Home: index.md
  - Ejercicio1:
      - ejercicio1.md
  - Ejercicio2:
      - ejercicio2.md
  - Ejercicio3:
      - ejercicio3.md
theme: readthedocs
