site_name: Documentaci√≥n
site_url: https://github.com/Gabriel221011/Documentacion
docs_dir: /paginas
site_dir: /docs

nav:
  - Home: index.md
  - VariasCosas:
      - varios.md
  - Otros:
      - otros.md

