site_name: Documentaci√≥n
site-url: https://github.com/Gabriel221011/Documentacion
site_dir: /docs
docs-dir: /paginas
nav:
  Home: index.md
  Varias-Cosas: varios.md
  Otras: otros.md
theme: readthedocs
